### ISSUE TITLE
Add ratelimited.me support

### ISSUE THREAD

**Issue by twilight-sparkle-irl** [ScoreUnder/pomfclip#3]
https://api.ratelimited.me/api/upload/pomf?key=

**Comment by ScoreUnder** [comment]
It looks like I'll need an account on that site to be able to test. I've signed up but since signups are vetted manually I don't know if/when I will get a login. In the meantime, if someone else has an account and can test the waters with this site, that would be a great help.

**Comment by ScoreUnder** [comment]
Sorry for taking so long to come back around to this. I've got an account and played around a little, and finally added it to the script according to how I understand it.
